api_platform:
    title: 'Work Entries API'
    version: '1.0.1'
    enable_swagger_ui: true
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    formats:
        jsonld: ['application/ld+json']
        json:   ['application/json']
        html:   ['text/html']
